language: node_js
node_js: node
install:
  - npm install
script:
  - npm run build:gh-pages -- --spa
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: ./dist
  on:
    branch: master
